// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFbqjAfarSNCnaO0fMgWTcxYaL1m33sUs',
    appId: '1:888288854479:web:6cc2fd3866e1ad39c852ba',
    messagingSenderId: '888288854479',
    projectId: 'event-app-3ebee',
    authDomain: 'event-app-3ebee.firebaseapp.com',
    storageBucket: 'event-app-3ebee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK1i2cHrF_t2lLx-brh92fzGftQM93bqU',
    appId: '1:888288854479:android:2c9c7101e476cad2c852ba',
    messagingSenderId: '888288854479',
    projectId: 'event-app-3ebee',
    storageBucket: 'event-app-3ebee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGFZdvFyvVYKwn2fjASxqm1aWoVmXVM6g',
    appId: '1:888288854479:ios:5b6b23b10f74872bc852ba',
    messagingSenderId: '888288854479',
    projectId: 'event-app-3ebee',
    storageBucket: 'event-app-3ebee.firebasestorage.app',
    iosClientId: '888288854479-2qts7u87de0lg5na1pug56l7gucb07ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGFZdvFyvVYKwn2fjASxqm1aWoVmXVM6g',
    appId: '1:888288854479:ios:5b6b23b10f74872bc852ba',
    messagingSenderId: '888288854479',
    projectId: 'event-app-3ebee',
    storageBucket: 'event-app-3ebee.firebasestorage.app',
    iosClientId: '888288854479-2qts7u87de0lg5na1pug56l7gucb07ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFbqjAfarSNCnaO0fMgWTcxYaL1m33sUs',
    appId: '1:888288854479:web:11e81946ad466e2fc852ba',
    messagingSenderId: '888288854479',
    projectId: 'event-app-3ebee',
    authDomain: 'event-app-3ebee.firebaseapp.com',
    storageBucket: 'event-app-3ebee.firebasestorage.app',
  );
}
